### ISSUE TITLE
Question about vendor extension folder

### ISSUE THREAD

**Issue by Unknow-max** [HugoGiraudel/sass-boilerplate#35]
**Hi,**
I have a question about the eighth folder, called vendor extension.
Now, In my project I have two vendor files, **magnific popup** (a simple Jquery popup plugin) and **balloon.css** (a tooltip library).
For both of them I have a very few custom styles, 

### for example this is the extended styles for the tooltip library:
```scss

/*-------------------------------------
  Magnific Popup Video Animation
-------------------------------------*/

/* Overlay */
.mfp-bg {
  opacity: 0;
  transition: opacity trs(sm);

  &.mfp-ready {
    opacity: .6;
  }

  &.mfp-removing {
    opacity: 0;
  }
}

/* Content*/
.mfp-content {
  opacity: 0;
  transition: opacity trs(md);

  .mfp-ready & {
    opacity: 1;
  }

  .mfp-removing & {
    opacity: 0;
  }
}
```

### And this styles for the popup:
```scss
/*-------------------------------------
  Extend Tooltip Css
-------------------------------------*/

.tooltip {
  --balloon-font-size: 1.3rem;

  &::after {
    padding: .75rem 1.3rem !important;
  }
}

/* attach the arrow (::before) to the body (::after) */
[data-balloon-pos="right"]::before {
  transform: translate(.1rem, -50%) !important;
}

[data-balloon-pos="down"]::before {
  transform: translate(-50%, .1rem) !important;
}

.tooltip--error {
--balloon-color: #{color(red)};
}
```
*Like you see, not a big amount of CSS.*

Currently I have this styles in my _base.scss file (at the bottom of it) and I don't know if is very needed a eighth folder, with a file for each vendor. I thought that maybe I can create only one file called "_extend-vendors.scss" for collect all of them and put it in base folder.
